import{analyze,pdfText}from './engine.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={data:JSON.parse(localStorage.getItem('ss:data')||'null'),sessions:JSON.parse(localStorage.getItem('ss:sessions')||'[]'),mode:'dashboard',card:0,quiz:0,score:0,flipped:false,timer:1500,remaining:1500,running:false};
const save=()=>{localStorage.setItem('ss:data',JSON.stringify(state.data));localStorage.setItem('ss:sessions',JSON.stringify(state.sessions))};
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function go(mode){state.mode=mode;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${mode}`));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===mode));render()}
function render(){const d=state.data,s=state.sessions;$('#metricDocs').textContent=d?'1':'0';$('#metricWords').textContent=d?d.words.toLocaleString():'0';$('#metricSessions').textContent=s.length;$('#metricAccuracy').textContent=s.length?Math.round(s.reduce((a,x)=>a+x.accuracy,0)/s.length)+'%':'--';if(d){$('#docTitle').textContent=d.title||'Study material';$('#summary').innerHTML=d.summary.map(x=>`<div class="item"><div>${esc(x)}</div><span class="pill">key idea</span></div>`).join('');$('#concepts').innerHTML=d.concepts.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong><small>${x.count} mentions</small></div><span class="pill">priority</span></div>`).join('');$('#topics').innerHTML=d.topics.map(x=>`<span class="pill">${esc(x)}</span>`).join('');$('#cardsCount').textContent=d.flashcards.length;$('#quizCount').textContent=d.quiz.length;$('#wordCount').textContent=d.words.toLocaleString();$('#cardArea').innerHTML=d.flashcards.length?`<div class="flash"><div><small class="muted">Card ${state.card+1} of ${d.flashcards.length}</small><h2>${esc(state.flipped?d.flashcards[state.card].a:d.flashcards[state.card].q)}</h2><p class="muted">Click reveal to switch sides</p></div></div>`:'<div class="empty">Generate a study set first.</div>';renderQuiz();}else{$('#summary').innerHTML='<div class="empty">Import material to build your workspace.</div>';$('#concepts').innerHTML='<div class="empty">Your concept map will appear here.</div>';$('#topics').innerHTML='';$('#cardArea').innerHTML='<div class="empty">No flashcards yet.</div>';$('#quizArea').innerHTML='<div class="empty">No quiz yet.</div>'}renderProgress()}
function renderQuiz(){const q=state.data?.quiz?.[state.quiz];if(!q){$('#quizArea').innerHTML='<div class="empty">No recall questions available.</div>';return}$('#quizArea').innerHTML=`<p class="muted">Question ${state.quiz+1} of ${state.data.quiz.length}</p><h3>${esc(q.q)}</h3>${q.options.map((o,i)=>`<button class="option" data-opt="${i}">${esc(o)}</button>`).join('')}<p id="quizFeedback" class="muted">Score: ${state.score}</p>`;$$('[data-opt]').forEach(b=>b.onclick=()=>{const i=+b.dataset.opt;if(i===q.answer){b.classList.add('correct');state.score++;toast('Correct recall');}else{b.classList.add('wrong');$$('[data-opt]')[q.answer]?.classList.add('correct');toast('Review this concept');}setTimeout(()=>{state.quiz++;if(state.quiz>=state.data.quiz.length){const acc=Math.round(state.score/state.data.quiz.length*100);state.sessions.push({date:Date.now(),minutes:5,accuracy:acc});save();state.quiz=0;state.score=0;toast(`Quiz complete: ${acc}%`)}render()},650)})}
function renderProgress(){const s=state.sessions;$('#history').innerHTML=s.length?s.slice().reverse().slice(0,8).map(x=>`<div class="item"><div><strong>${new Date(x.date).toLocaleDateString()}</strong><small>${x.minutes} min session</small></div><span class="pill">${x.accuracy}% recall</span></div>`).join(''):'<div class="empty">Complete a session to build your learning history.</div>';const acc=s.length?Math.round(s.reduce((a,x)=>a+x.accuracy,0)/s.length):0;$('#masteryBar').style.width=acc+'%';$('#mastery').textContent=acc+'%';}
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[c]))}
async function importFile(file){try{let text='';if(file.type==='application/pdf'||file.name.endsWith('.pdf'))text=await pdfText(file);else text=await file.text();$('#material').value=text;$('#docName').value=file.name.replace(/\.[^.]+$/,'');toast('Material loaded. Run analysis.')}catch(e){toast(e.message)}}
$('#analyze').onclick=()=>{const text=$('#material').value.trim();if(text.length<80){toast('Add more material before analysis.');return}state.data=Object.assign(analyze(text),{title:$('#docName').value.trim()||'Untitled study set'});state.card=0;state.quiz=0;state.score=0;save();go('dashboard');toast('Study intelligence ready')};
$('#demo').onclick=()=>{$('#docName').value='Operating Systems Fundamentals';$('#material').value=`Process Management\nA process is a program in execution. A process contains its program code, current activity, stack, heap and operating system resources. Process scheduling is the method used by the operating system to select a process for CPU execution.\n\nMemory Management\nVirtual memory is a memory management technique that gives programs the impression of a large, continuous memory space. Paging divides physical memory into fixed-size blocks called frames and logical memory into pages.\n\nScheduling\nRound Robin is a scheduling algorithm where each process receives a fixed time slice. Context switching is the process of saving the state of one process and loading the state of another process.`;toast('Demo material loaded')};
$('#material').addEventListener('input',()=>$('#liveWords').textContent=$('#material').value.trim().split(/\s+/).filter(Boolean).length.toLocaleString());
const drop=$('#drop');['dragover','dragenter'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&importFile(e.dataTransfer.files[0]));$('#file').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);
$$('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#reveal').onclick=()=>{if(!state.data?.flashcards.length)return;state.flipped=!state.flipped;render()};$('#nextCard').onclick=()=>{if(state.data){state.card=(state.card+1)%state.data.flashcards.length;state.flipped=false;render()}};$('#prevCard').onclick=()=>{if(state.data){state.card=(state.card-1+state.data.flashcards.length)%state.data.flashcards.length;state.flipped=false;render()}};$('#startSprint').onclick=()=>{state.running=!state.running;$('#startSprint').textContent=state.running?'Pause':'Start sprint'};$('#resetSprint').onclick=()=>{state.running=false;state.remaining=state.timer;$('#startSprint').textContent='Start sprint';tick()};$$('[data-min]').forEach(b=>b.onclick=()=>{state.timer=+b.dataset.min*60;state.remaining=state.timer;$$('[data-min]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tick()});function tick(){const m=Math.floor(state.remaining/60),sec=state.remaining%60;$('#clock').textContent=`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;$('#sprintBar').style.width=((state.timer-state.remaining)/state.timer*100)+'%'}setInterval(()=>{if(state.running&&state.remaining>0){state.remaining--;tick()}else if(state.running&&state.remaining===0){state.running=false;state.sessions.push({date:Date.now(),minutes:Math.round(state.timer/60),accuracy:0});save();toast('Sprint complete');$('#startSprint').textContent='Start sprint'}},1000);
$('#globalSearch').oninput=e=>{const q=e.target.value.toLowerCase();if(q&&state.data){go('dashboard');toast(state.data.concepts.some(x=>x.name.toLowerCase().includes(q))?'Concept found in your study set':'Search is limited to your current study set')}};document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==$('#globalSearch')){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape')$('#globalSearch').blur();if(e.key===' '&&state.mode==='sprint'&&document.activeElement.tagName!=='TEXTAREA'){e.preventDefault();$('#startSprint').click()}});$('#clearData').onclick=()=>{localStorage.clear();location.reload()};$('#focusMaterial').onclick=()=>go('material');
const pdf=document.createElement('script');pdf.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';pdf.onload=()=>window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';document.head.appendChild(pdf);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});tick();render();
