const STOP=new Set('the a an and or but if then than with from into onto for of to in on at by is are was were be been being this that these those it its as about through during after before between not no yes very more most some such their there here you your our we they them he she his her what which when where how why who will would should could can may might do does did done have has had having'.split(' '));
const clean=s=>s.replace(/\s+/g,' ').trim();
function sentences(text){return clean(text).match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]}
function words(text){return (text.toLowerCase().match(/[a-z][a-z0-9'-]{2,}/g)||[]).filter(w=>!STOP.has(w))}
function freq(text){const m={};words(text).forEach(w=>m[w]=(m[w]||0)+1);return m}
function titleCase(s){return s.replace(/\b\w/g,x=>x.toUpperCase())}
function scoreSentences(text){const ss=sentences(text),f=freq(text);return ss.map((s,i)=>{const ws=words(s);let score=ws.reduce((n,w)=>n+(f[w]||0),0)/(ws.length||1);if(i<3)score*=1.15;if(s.length>220)score*=.75;if(/\b(is|means|refers to|defined as|known as)\b/i.test(s))score*=1.4;return{sentence:clean(s),score}}).sort((a,b)=>b.score-a.score)}
function definitions(text){const out=[];for(const s of sentences(text)){const m=s.match(/^(.{2,70}?)\s+(?:is|are|means|refers to|is defined as|can be defined as)\s+(.{10,220})[.!?]?$/i);if(m)out.push({term:clean(m[1]),definition:clean(m[2])});}return out.slice(0,20)}
function concepts(text){const f=freq(text);return Object.entries(f).filter(([w,n])=>n>=2&&w.length>4).sort((a,b)=>b[1]-a[1]).slice(0,18).map(([w,n])=>({name:titleCase(w),count:n}))}
function topics(text){const lines=text.split(/\n+/).map(clean).filter(Boolean),heads=lines.filter(x=>x.length<90&&(/^[A-Z][^.!?]{2,70}$/.test(x)||/^\d+[.)]\s/.test(x)));if(heads.length)return heads.slice(0,12);return concepts(text).slice(0,8).map(x=>x.name)}
export function analyze(text){text=clean(text);const ss=sentences(text),defs=definitions(text),cs=concepts(text),ts=topics(text),ranked=scoreSentences(text);const summary=ranked.slice(0,Math.min(5,Math.max(2,Math.ceil(ss.length*.18)))).sort((a,b)=>ss.indexOf(ss.find(x=>x===a.sentence))-ss.indexOf(ss.find(x=>x===b.sentence))).map(x=>x.sentence);const cards=defs.map(d=>({q:`What is ${d.term}?`,a:d.definition}));ranked.slice(0,12).forEach(x=>{if(!cards.some(c=>c.a===x.sentence)&&x.sentence.length>45)cards.push({q:'Explain this key idea in your own words.',a:x.sentence})});const quiz=buildQuiz(defs,cs);return{words:words(text).length,sentences:ss.length,summary,definitions:defs,concepts:cs,topics:ts,flashcards:cards.slice(0,18),quiz,priority:cs.slice(0,8)}}
function buildQuiz(defs,cs){const qs=[];defs.slice(0,8).forEach((d,i)=>{const pool=defs.filter(x=>x.term!==d.term).map(x=>x.definition).slice(0,3);if(pool.length<2)return;const opts=[d.definition,...pool].sort(()=>Math.random()-.5);qs.push({q:`Which statement best describes ${d.term}?`,options:opts,answer:opts.indexOf(d.definition),topic:d.term})});cs.slice(0,5).forEach(c=>{const wrong=cs.filter(x=>x.name!==c.name).slice(0,3).map(x=>x.name);if(wrong.length<2)return;const opts=[c.name,...wrong].sort(()=>Math.random()-.5);qs.push({q:`Which concept appears most prominently in the material?`,options:opts,answer:opts.indexOf(c.name),topic:c.name})});return qs.slice(0,10)}
export async function pdfText(file){if(!window.pdfjsLib)throw new Error('PDF engine is still loading. Try again in a moment.');const data=await file.arrayBuffer();const pdf=await window.pdfjsLib.getDocument({data}).promise;let text='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent();text+=content.items.map(x=>x.str).join(' ')+'\n';}return text}
